services:
  db:
    image: steven462/db:v1
    ports: 
      - "3333:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      replicas: 1


  proyectos:
    image: steven462/proyectos:v1
    depends_on:
      - db
      - usuarios
    ports:
      - "8001:8001"
    deploy:
      replicas: 1


  tareas:
    image: steven462/tareas:v1
    depends_on:
      - db
      - proyectos
    ports:
      - "8002:8002"
    deploy:
      replicas: 1


      
  tareasasignadas:
    image: steven462/tareasasignadas:v1
    depends_on:
      - db
      - usuarios
      - proyectos
    ports:
      - "8003:8003"
    deploy:
      replicas: 1



  usuarios:
    image: steven462/users:v1
    depends_on:
      - db
    ports:
      - "8000:8000"
    deploy:
      replicas: 1


  web:
    image: steven462/front:v1
    ports:
      - "8080:80"
    deploy:
      replicas: 1