services:
  db:
    image: marchimself/appdb:latest
    ports: 
      - "3333:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 10s
      retries: 10

  proyectos:
    image: marchimself/proyectosmicrsrv:latest
    depends_on:
      - db
      - usuarios
    ports:
      - "8001:8001"

  tareas:
    image: marchimself/tareasasigmicrsrv:latest
    depends_on:
      - db
      - proyectos
    ports:
      - "8002:8002"

  tareasasignadas:
    image: marchimself/tareasasigmicrsrv:v3
    depends_on:
      - db
      - usuarios
      - proyectos
    ports:
      - "8003:8003"


  usuarios:
    image: marchimself/usuariosmicrsrv:v2
    depends_on:
      - db
    ports:
      - "8000:8000"

  web:
    image: frontlocal
    ports:
      - "8080:80"